### ISSUE TITLE
Time elapsed?

### ISSUE THREAD

**Issue by mantazzo** [clandrew/wdrp#2]
Hey there,
I want to thank you for this nice plugin, however I do have a suggestion.
Would it be hard for you to implement "time elapsed" display also? From what I checked in the documentation you'd only need to provide a "startTimestamp" to show how much time has passed. Would be a nice little add-on to the plugin.
(Also, you forget to mention in the ReadMe that if you want to have a logo in Discord pop-up you also need to upload image named "winamp-logo" to "Rich Presence -> Art Assets" part of Developer section.)
Thanks.

**Comment by clandrew** [comment]
Time elapsed would be a good idea! You're right, it shouldn't be too bad to add.

Thanks for pointing that out in the readme, I'll get that updated.

**Comment by clandrew** [comment]
Update- I've added the ability to show elapsed time. It's in this release:
https://github.com/clandrew/wdrp/releases/tag/1.3

I've taken some time to test it a fair bit locally but for sure let me know if it works for you or if you experience any issues. Thanks again for the suggestion!

**Comment by clandrew** [comment]
Closing this as there is not an action left for me, but of course feel free to reactivate or get in touch as needed
