### ISSUE TITLE
How do you even get winamp ????

### ISSUE THREAD

**Issue by marttoygoy4** [clandrew/wdrp#20]
How do you even get winamp ???????
Windows 95 newbie* here :)

_*edit: Sorry, gotta keep clean language in this house_

**Comment by clandrew** [comment]
Normally I'd point people toward the official web site [https://www.winamp.com](https://www.winamp.com), But the link got broken when Winamp got acquired by a new company.

For now, you can download the latest version 5.666 at the Internet Archive 
[https://archive.org/download/winamp5666_full_all_redux](https://archive.org/download/winamp5666_full_all_redux)

If you want to run Winamp in your Windows 95 environment you will need an older version. They dropped support for Windows 95 a while ago. Afaik you would need around version 2.9x.

**Comment by clandrew** [comment]
I don't see anything left to do here so I'm closing this issue but feel free to get in touch if you need anything else
