### ISSUE TITLE
No file named gen_DiscordRichPresence.dll

### ISSUE THREAD

**Issue by Antropoliid** [clandrew/wdrp#5]
Theres no file named gen_DiscordRichPresence.dll in download

**Comment by clandrew** [comment]
Hi, thanks for getting in touch. Did you download one of the "releases" from here?
https://github.com/clandrew/wdrp/releases

**Comment by clandrew** [comment]
I don't see an action for me here, but feel free to re-activate or get in touch if this doesn't work. Closing
