### ISSUE TITLE
Update readme to indicate desktop client is required for adding an application image

### ISSUE THREAD

**Issue by JonnoFTW** [clandrew/wdrp#6]
Can you include the application image you used for your discord application?

**Comment by kamfretoz** [comment]
You can manually add the icon yourself (you can even use custom icon).

Here's the step:
1. On your Discord's App page, go to `Rich Pressence -> Art Assets`
2. Add any icon you want, and make sure to name it `winamp-logo`
3. Restart Winamp (or change the music to refresh the Rich Presence)
4. All set!

![fh8lS4Z9tu](https://user-images.githubusercontent.com/14798312/65988276-b6e02d00-e4b1-11e9-864d-3c1567726b55.png)

![chrome_95pMbphW8a](https://user-images.githubusercontent.com/14798312/65988224-a4fe8a00-e4b1-11e9-98b6-089ba9df2c65.png)

**Comment by JonnoFTW** [comment]
Thanks, I got it working. It should probably note in the readme that you need to be using the desktop client for this to work.

**Comment by clandrew** [comment]
Glad this got resolved for you! 
I don't know of a way to include an image with the re-distributable that would automagically hook it up end-to-end, but yeah that's the way to set it up.
That's a good point, I should update the readme. Re-opening to track my doing that

**Comment by clandrew** [comment]
@JonnoFTW I just tested things a bit, and I couldn't find a difference-worth-pointing-out between the desktop and the web app. 
Can you clarify what you meant? I don't have the mobile app handy to test

**Comment by clandrew** [comment]
I don't see an action here so closing
